
import java.awt.List;
import java.util.ArrayList;
import javax.script.ScriptException;
import java.text.DecimalFormat;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zooe_
 */
public class Ventana extends javax.swing.JFrame {
    private String textoActual;
    private ArrayList<Double> numeros = new ArrayList<>();
    private double result;
    private String operador;

    /**
     * 
     * Creates new form Ventana
     */
    
    public Ventana() {
        initComponents();
        display.setFocusable(true);
        display.requestFocusInWindow();
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt){
                char c = evt.getKeyChar();
                
                if(!Character.isDigit(c) && "+-*/.".indexOf(c) == -1){
                    evt.consume();
                }
            }
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt){
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
                    igualActionPerformed(null);
                }
                else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE ||
                        evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE){
                        borrarActionPerformed(null);
                }
            }
        });
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt){
                char c = evt.getKeyChar();
                
                if( c == '.'){
                    String textoActual = display.getText();
                    String[] operandos = textoActual.split("[-+*/]");
                    String ultimoNumero = operandos.length > 0 ? operandos[operandos.length - 1] : "";
                    
                    if(ultimoNumero.contains(".")){
                        evt.consume();
                        return;
                    }
                }
                if(!Character.isDigit(c) && "+-*/.".indexOf(c) == -1){
                    evt.consume();
                }
            }
            
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt){
                if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
                    igualActionPerformed(null);
                }else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE ||
                        evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE){
                    borrarActionPerformed(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        display = new javax.swing.JTextField();
        borraruno = new javax.swing.JButton();
        division = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        numeber9 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        por = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        number0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        borraruno.setBackground(new java.awt.Color(68, 152, 236));
        borraruno.setBackground(new java.awt.Color(68, 152, 236));
        borraruno.setText("Borrar");
        borraruno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        borraruno.setForeground(new java.awt.Color(0, 0, 0));
        borraruno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/borrar.png"))); // NOI18N
        borraruno.setText("Borrar");
        borraruno.setMargin(new java.awt.Insets(5, 14, 5, 14));
        borraruno.setMaximumSize(new java.awt.Dimension(32, 32));
        borraruno.setMinimumSize(new java.awt.Dimension(32, 32));
        borraruno.setPreferredSize(new java.awt.Dimension(32, 32));
        borraruno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarunoActionPerformed(evt);
            }
        });

        division.setBackground(new java.awt.Color(68, 152, 236));
        division.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        division.setForeground(new java.awt.Color(0, 0, 0));
        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(68, 152, 236));
        borrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrar.setForeground(new java.awt.Color(0, 0, 0));
        borrar.setText("C");
        borrar.setAlignmentY(0.0F);
        borrar.setMinimumSize(new java.awt.Dimension(39, 39));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        number7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        numeber9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numeber9.setText("9");
        numeber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeber9ActionPerformed(evt);
            }
        });

        number8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number8.setText("8");
        number8.setPreferredSize(new java.awt.Dimension(32, 32));
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        por.setBackground(new java.awt.Color(68, 152, 236));
        por.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        por.setForeground(new java.awt.Color(0, 0, 0));
        por.setText("x");
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });

        number4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number4.setText("4");
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number1.setText("1");
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number6.setText("6");
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        menos.setBackground(new java.awt.Color(68, 152, 236));
        menos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menos.setForeground(new java.awt.Color(0, 0, 0));
        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        mas.setBackground(new java.awt.Color(68, 152, 236));
        mas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mas.setForeground(new java.awt.Color(0, 0, 0));
        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        number3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number3.setText("3");
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        number5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number5.setText("5");
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number2.setText("2");
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(68, 152, 236));
        igual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        igual.setForeground(new java.awt.Color(0, 0, 0));
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        punto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        number0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number0.setText("0");
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(display, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(borraruno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(division, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(borrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(numeber9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(por, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(menos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(mas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(igual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(punto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(number0, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeber9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borraruno, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(por, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borraruno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeber9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(punto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(number0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        display.setText("");
        result = 0;
        numeros.clear();
    }//GEN-LAST:event_borrarActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
         textoActual = display.getText(); 
        display.setText(textoActual + "7");
    }//GEN-LAST:event_number7ActionPerformed

    private void numeber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeber9ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "9");
    }//GEN-LAST:event_numeber9ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "8");
    }//GEN-LAST:event_number8ActionPerformed

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
       textoActual = display.getText(); 
        display.setText(textoActual + "*");
    }//GEN-LAST:event_porActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "4");
    }//GEN-LAST:event_number4ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "1");
    }//GEN-LAST:event_number1ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "6");
    }//GEN-LAST:event_number6ActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "-");
    }//GEN-LAST:event_menosActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "+");

    }//GEN-LAST:event_masActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "3");
    }//GEN-LAST:event_number3ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        textoActual = display.getText(); 
        display.setText(textoActual + "5");
    }//GEN-LAST:event_number5ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
         textoActual = display.getText(); 
        display.setText(textoActual + "2");
    }//GEN-LAST:event_number2ActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
   
        textoActual = display.getText().trim();
        
        if (textoActual.isEmpty()){
            display.setText("0.0");
            return;
        }
                
        if("+-*.".contains(String.valueOf(textoActual.charAt(textoActual.length()-1)))){
            textoActual= textoActual.substring(0, textoActual.length() -1);
        }
        numeros.clear();
        if(textoActual.contains("+") || textoActual.contains("-") || textoActual.contains("*") || textoActual.contains("/")){
            String[] partes = textoActual.split("(?<=[-+*/])|(?=[-+*/])");
            try{
                for(int i = 0; i < partes.length; i ++){
                    if(i % 2 == 0 ){
                        numeros.add(Double.parseDouble(partes[i]));
                    }
                }
                double resultado = numeros.get(0);
                
                for(int i = 1; i < numeros.size(); i++){
                    String operadorLocal = partes[i * 2 -1];
                    double numero = numeros.get(i);
                    switch(operadorLocal){
                        case "+": resultado += numero; break;
                        case "-": resultado -= numero; break;
                        case "*": resultado *= numero; break;
                        case "/": 
                            if(numero != 0){
                                resultado /= numero;
                            }else{
                                display.setText("Error: Div / 0 ");
                                return;
                            }
                            break;
                    }
                }
                DecimalFormat df = new DecimalFormat("#.####");
                display.setText(df.format(resultado));
            }catch(NumberFormatException e){
                display.setText("Error de formato");
            }
        }else{
            try{
                double numero1 = Double.parseDouble(textoActual);
                 DecimalFormat df = new DecimalFormat("#.####");
                display.setText(df.format(numero1));
            }catch (NumberFormatException e){
                display.setText("Error");
            }
        }
    }//GEN-LAST:event_igualActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
         textoActual = display.getText();
         String[] operandos = textoActual.split("[-+*/]");
         String ultimoNumero = operandos.length > 0 ? operandos[operandos.length - 1] : "";
         
         if(!ultimoNumero.contains(".")){
             display.setText(textoActual + ".");
         }
    }//GEN-LAST:event_puntoActionPerformed

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
         textoActual = display.getText(); 
        display.setText(textoActual + "0");
    }//GEN-LAST:event_number0ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
       textoActual = display.getText(); 
       display.setText(textoActual + "/");
    }//GEN-LAST:event_divisionActionPerformed

    private void borrarunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarunoActionPerformed
        textoActual = display.getText(); 
        if (textoActual != null && !textoActual.isEmpty()) {
            textoActual = textoActual.substring(0, textoActual.length() - 1);
        }
        display.setText(textoActual);
    }//GEN-LAST:event_borrarunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton borraruno;
    private javax.swing.JTextField display;
    private javax.swing.JButton division;
    private javax.swing.JButton igual;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton numeber9;
    private javax.swing.JButton por;
    private javax.swing.JButton punto;
    // End of variables declaration//GEN-END:variables
}
